demo/rails/config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/captchas')
  resources :captchas,    only: [:index, :create]
  resources :v3_captchas, only: [:index, :create] do
    collection do
      post :create_multi
    end
  end
  resources :users
end

demo/rails/app/models/user.rb
class User < ActiveRecord::Base
end

demo/rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/rails/app/controllers/captchas_controller.rb
class CaptchasController < ApplicationController
  def index
  end

  def create
    if verify_recaptcha
      render plain: 'YES'
    else
      render plain: 'NO'
    end
  end
end

demo/rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if verify_recaptcha(model: @user, message: 'Error in passing CAPTCHA.') && @user.save
      redirect_to users_path, notice: "Saved"
    else
      render 'edit'
    end
  end
end

demo/rails/app/controllers/v3_captchas_controller.rb
class V3CaptchasController < ApplicationController
  def index
  end

  def create
    if verify_recaptcha(action: 'demo', minimum_score: 0.5)
      render plain: 'YES'
    else
      render plain: 'NO'
    end
  end

  def create_multi
    if verify_recaptcha(action: 'demo_a', minimum_score: 0.5) &&
       verify_recaptcha(action: 'demo_b', minimum_score: 0.5)
      render plain: 'YES'
    else
      render plain: 'NO'
    end
  end
end

demo/rails/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/rails/app/views/captchas/index.html.erb
<% if params[:multi] %>
  <script type="text/javascript">
    var verifyCallback = function(response) {
      alert(response);
    };
    var widgetId1;
    var widgetId2;
    var onloadCallback = function() {
      // Renders the HTML element with id 'example1' as a reCAPTCHA widget.
      // The id of the reCAPTCHA widget is assigned to 'widgetId1'.
      widgetId1 = grecaptcha.render('example1', {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>",
        'theme' : 'light'
      });
      widgetId2 = grecaptcha.render(document.getElementById('example2'), {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>"
      });
      grecaptcha.render('example3', {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>",
        'callback' : verifyCallback,
        'theme' : 'dark'
      });
    };
  </script>

  <%= form_tag "/captchas" do |f| %>
    <div id="example1"></div>
    <%= submit_tag %>
  <% end %>
  <%= form_tag "/captchas" do %>
    <div id="example2"></div>
    <%= submit_tag %>
  <% end %>
  <%= form_tag "/captchas" do %>
    <div id="example3"></div>
    <%= submit_tag %>
  <% end %>
  <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
<% elsif params[:invisible] %>
  <%= form_tag "/captchas", id: "invisible-recaptcha-form" do %>
    <%= invisible_recaptcha_tags text: 'Save changes' %>
  <% end %>
<% else %>
  <%= form_tag "/captchas" do %>
    <%= recaptcha_tags %>
    <%= submit_tag %>
  <% end %>
<% end %>
<%= link_to 'Single ?', '?' if params[:multi] or params[:invisible] %>
<%= link_to 'Multi ?', '?multi=1' unless params[:multi] %>
<%= link_to 'Invisible ?', '?invisible=1' unless params[:invisible] %>

demo/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |k,v| %>
  <div><%= k %>: <%= v %></div>
<% end %>

<%= yield %>

</body>
</html>

demo/rails/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= recaptcha_tags %>
  <%= f.submit %>
<% end %>

demo/rails/app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr><td><%= link_to user.name, edit_user_path(user) %></td></tr>
  <% end %>
</table>

demo/rails/app/views/v3_captchas/index.html.erb
<% if params[:multi] %>
  <%= form_tag "/#{controller_name}/create_multi" do |f| %>
    <%= recaptcha_v3 action: 'demo_a' %>
    <%= recaptcha_v3 action: 'demo_b', external_script: false %>
    <%= submit_tag %>
  <% end %>

<% elsif params[:custom_callback] %>
  <script type="text/javascript">
    var myCallback = function(action, response) {
      alert(`Response for ${action} action: ${response}`);
    };
  </script>
  <%= recaptcha_v3 action: 'demo', callback: 'myCallback' %>

<% elsif params[:execute_on_submit] %>
  <%= form_tag "/#{controller_name}" do %>
    <%= recaptcha_v3 action: 'demo' %>
    <%= submit_tag %>
  <% end %>

  <script type="text/javascript">
    const form = document.forms.item(0)
    const hiddenInput = document.getElementById('g-recaptcha-response-demo')
    form.addEventListener('submit', async function(e) {
      e.preventDefault();
      console.log('Submitted form. Getting fresh reCAPTCHA response token…')
      const response = await window.executeRecaptchaForDemoAsync()
      console.log(`Response was: ${response}`)
      hiddenInput.value = response
      form.submit()
    });
  </script>

<% else %>
  <%= form_tag "/#{controller_name}" do %>
    <%= recaptcha_v3 action: 'demo' %>
    <%= submit_tag %>
  <% end %>
<% end %>

<%= link_to 'Single', '?' if params[:multi] || params[:custom_callback] || params[:execute_on_submit] %>
<%= link_to 'Multi',             '?multi=1'             unless params[:multi] %>
<%= link_to 'Custom callback',   '?custom_callback=1'   unless params[:custom_callback] %>
<%= link_to 'Execute on submit', '?execute_on_submit=1' unless params[:execute_on_submit] %>